import { type DefaultTheme } from 'vitepress'
const Nodejs60DaysDocs: DefaultTheme.SidebarItem = {
  base: '/Nodejs60DaysDocs/days',
  text: '60天学会Node.js全栈开发',
  items: [
    {
      text: '📚 基础入门（Day 01-15）',
      collapsed: false,
      items: [
        { text: '01-环境搭建与 Node.js 初印象', link: '/day-01/' },
        { text: '02-模块系统与包管理', link: '/day-02/' },
        { text: '03-Node.js fs、path、os', link: '/day-03/' },
        { text: '04-Node.js events、stream、Buffer', link: '/day-04/' },
        { text: '05-事件循环深度解析', link: '/day-05/' },
        { text: '06-异步编程模式', link: '/day-06/' },
        { text: '07-HTTP 协议基础', link: '/day-07/' },
        { text: '08-构建 REST API（上）', link: '/day-08/' },
        { text: '09-构建 REST API（下）', link: '/day-09/' },
        { text: '10-🏆里程碑：迷你项目 Review', link: '/day-10/' },
        { text: '11-TypeScript 在 Node.js 中的使用', link: '/day-11/' },
        { text: '12-RESTful API 设计原则', link: '/day-12/' },
        { text: '13-进程管理与 Worker Threads', link: '/day-13/' },
        { text: '14-错误处理与调试技巧', link: '/day-14/' },
        { text: '15-🎯阶段一总结与测验', link: '/day-15/' },
      ],
    },
    {
      text: '🏗️ NestJS 框架（Day 16-20）',
      collapsed: false,
      items: [
        { text: '16-入门：架构与核心概念', link: '/day-16/' },
        { text: '17-深入：请求生命周期', link: '/day-17/' },
        { text: '18-数据验证与 DTO', link: '/day-18/' },
        { text: '19-异常处理与响应标准化', link: '/day-19/' },
        { text: '20-🏆里程碑：博客 API（无数据库版）', link: '/day-20/' },
      ],
    },
    {
      text: '🗄️ 数据库（Day 21-30）',
      collapsed: false,
      items: [
        { text: '21-数据库基础与 PostgreSQL', link: '/day-21/' },
        { text: '22-SQL 进阶：JOIN、子查询与聚合', link: '/day-22/' },
        { text: '23-SQL 进阶：索引与性能', link: '/day-23/' },
        { text: '24-数据库建模实战', link: '/day-24/' },
        { text: '25-Prisma ORM 入门', link: '/day-25/' },
        { text: '26-Prisma ORM 进阶', link: '/day-26/' },
        { text: '27-NestJS + Prisma 整合', link: '/day-27/' },
        { text: '28-分页、搜索与排序', link: '/day-28/' },
        { text: '29-数据库事务与并发控制', link: '/day-29/' },
        { text: '30-🏆 里程碑：博客系统 API 完整版', link: '/day-30/' },
      ],
    },
    {
      text: '🔒 安全与认证（Day 31-40）',
      collapsed: false,
      items: [
        { text: '31-认证基础：Session vs JWT', link: '/day-31/' },
        { text: '32-JWT 认证实战', link: '/day-32/' },
        { text: '33-RBAC 权限模型', link: '/day-33/' },
        { text: '34-OAuth 2.0 与第三方登录', link: '/day-34/' },
        { text: '35-Web 安全防护', link: '/day-35/' },
        { text: '36-Redis 基础与缓存策略', link: '/day-36/' },
        { text: '37-Redis 进阶应用', link: '/day-37/' },
        { text: '38-消息队列与异步任务', link: '/day-38/' },
        { text: '39-文件上传与存储', link: '/day-39/' },
        { text: '40-🏆 里程碑：安全加固版博客系统（v2.0）', link: '/day-40/' },
      ],
    },
    {
      text: '🚀 部署与运维（Day 41-45）',
      collapsed: false,
      items: [
        { text: '41-Docker 基础', link: '/day-41/' },
        { text: '42-Docker Compose 与多服务编排', link: '/day-42/' },
        { text: '43-CI/CD 流水线（GitHub Actions）', link: '/day-43/' },
        { text: '44-云部署实战', link: '/day-44/' },
        { text: '45-日志、监控与健康检查', link: '/day-45/' },
      ],
    },
    {
      text: '💼 实战项目（Day 46-55）',
      collapsed: false,
      items: [
        { text: '46-项目规划与架构设计', link: '/day-46/' },
        { text: '47-项目脚手架与基础设施', link: '/day-47/' },
        { text: '48-用户系统与团队管理', link: '/day-48/' },
        { text: '49-项目与任务 CRUD', link: '/day-49/' },
        { text: '50-看板与列表视图 API', link: '/day-50/' },
        { text: '51-实时通信', link: '/day-51/' },
        { text: '52-通知与异步任务', link: '/day-52/' },
        { text: '53-数据看板与统计', link: '/day-53/' },
        { text: '54-前端集成与联调', link: '/day-54/' },
        { text: '55-🏆 里程碑：SaaS 任务管理平台部署上线', link: '/day-55/' },
      ],
    },
    {
      text: '🎯 进阶与总结（Day 56-60）',
      collapsed: false,
      items: [
        { text: '56-测试策略与实战', link: '/day-56/' },
        { text: '57-性能优化', link: '/day-57/' },
        { text: '58-系统设计思维', link: '/day-58/' },
        { text: '59-简历项目包装与面试准备', link: '/day-59/' },
        { text: '60-🎯 总结与进阶路线', link: '/day-60/' },
      ],
    },
  ],
}

export default Nodejs60DaysDocs
